apps/user/urls.py
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from django.urls import path
from drf_yasg import openapi
from .views import ( 
    IndexView,
    RegisterView, 
    LoginView, 
    LogoutView, 
    PasswordResetView, 
    ResetNewPasswordView, 
    CheckVerifyCodeView, 
)

schema_view = get_schema_view(
    openapi.Info(
        title="Rest Api",
        default_version='v1',
        description="API",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="claymrx571@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

app_name = 'accounts'
urlpatterns += [
    path('', IndexView.as_view(), name='index'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='password-reset'),
    path('reset-new-password/<uuid:uuid>/', ResetNewPasswordView.as_view(), name='reset-new-password'),
    path('check-verify-email/<uuid:uuid>/', CheckVerifyCodeView.as_view(), name='check-verify-code'),
]

core/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.user.urls')),
    path('course/', include('apps.useradmin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/accounts/login.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<meta charset="utf-8">
	<title>Online Course</title>
	<meta http-equiv="x-ua-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co">
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive">
	<meta name="author" content="freehtml5.co">
	<meta property="og:title" content="">
	<meta property="og:image" content="">
	<meta property="og:url" content="">
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/imgs/mrx.jpg' %}">
	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
	<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	</head>
    <body>
		
	<div class="fh5co-loader"></div>
	
	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-xs-1">
						<div id="fh5co-logo"><a href="{% url 'accounts:index' %}">Course</a></div>
					</div>
					<div class="col-xs-11 text-right menu-1">
						<ul>
							<li><a href="{% url 'categories' %}">Category</a></li>
							<li><a href="{% url 'prices' %}">Price</a></li>
							<li><a href="{% url 'blog' %}">Blog</a></li>
							<li><a href="{% url 'contact' %}">Contact</a></li>
							<li class="btn-cta"><a href="{% url 'accounts:login' %}"><span>Login</span></a></li>
							<li class="btn-cta"><a href="{% url 'accounts:register' %}"><span>Register</span></a></li>
						</ul>
					</div>
				</div>	
			</div>
		</div>
	</nav>

	<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url({% static 'assets/imgs/kurs.png' %});" data-stellar-background-ratio="0.5">
	<div class="overlay">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Login to Your Account</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	</header>
    
    <section class="login-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="login-card">
                        <form method="post" class="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="phone" placeholder="Phone Number" required>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Password" required>
                            </div>
                            <div class="login-options">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="check" name="check">
                                    <label class="form-check-label" for="check">Check</label>
                                </div>
                                <a href="{% url 'accounts:password-reset' %}" class="forgot-password">Forgot password?</a>
                            </div>
                            <button type="submit" class="btn btn-primary login-btn"> Log in</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer id="fh5co-footer" role="contentinfo">
		<div class="container">
			<div class="row row-pb-md justify-content-center text-center">
				<div class="col-md-3 fh5co-widget">
					<h4>About</h4>
					<p>You can learn programming in an online course. For example, you can learn c++, c#, python, java, javascript, php, etc. or learn through a tutorial</p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>Menu</h4>
					<ul class="fh5co-footer-links">
						<li><a href="{% url 'accounts:index' %}">Course</a></li>
						<li><a href="{% url 'categories' %}">Category</a></li>
						<li><a href="{% url 'prices' %}">Price</a></li>
						<li><a href="{% url 'blog' %}">Blog</a></li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>

			<div class="row copyright">
				<div class="col-md-12 text-center">
					<p>
						<ul class="fh5co-social-icons">
							<li><a href="https://t.me/musulmon_0319" target="_blank"><i class="fa-brands fa-telegram"></i></a></li>
							<li><a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
							<li><a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
							<li><a href="https://freehtml5.co/" target="_blank"><i class="fa-brands fa-google"></i></a></li>
						</ul>
					</p>
				</div>
			</div>
		</div>
    </footer>
	</div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
	<script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.stellar.min.js' %}"></script>
	<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
	<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'assets/js/magnific-popup-options.js' %}"></script>
	<script src="{% static 'assets/js/main.js' %}"></script>
	<script src="{% static 'assets/js/modernizr-2.6.2.min.js' %}"></script>
	<script src="{% static 'assets/js/respond.min.js' %}"></script>
</body>
</html>

templates/accounts/password_reset_check_verify_code.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<meta charset="utf-8">
	<title>Online Course</title>
	<meta http-equiv="x-ua-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co">
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive">
	<meta name="author" content="freehtml5.co">
	<meta property="og:title" content="">
	<meta property="og:image" content="">
	<meta property="og:url" content="">
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/imgs/mrx.jpg' %}">
	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
	<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	</head>
    <body>
		
	<div class="fh5co-loader"></div>
	
	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="top">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 text-right">
						<p class="num">Call: +998881031904</p>
						<ul class="fh5co-social">
							<li><a href="#"><i class="fa-brands fa-google"></i></a></li>
							<li><a href="#"><i class="fa-brands fa-github"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-xs-1">
						<div id="fh5co-logo"><a href="{% url 'accounts:index' %}">Course</a></div>
					</div>
					<div class="col-xs-11 text-right menu-1">
						<ul>
							<li><a href="{% url 'categories' %}">Category</a></li>
							<li><a href="{% url 'prices' %}">Price</a></li>
							<li><a href="{% url 'blog' %}">Blog</a></li>
							<li><a href="{% url 'contact' %}">Contact</a></li>
							<li class="btn-cta"><a href="{% url 'accounts:login' %}"><span>Login</span></a></li>
							<li class="btn-cta"><a href="{% url 'accounts:register' %}"><span>Register</span></a></li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</nav>

	<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url({% static 'assets/imgs/kurs.png' %});" data-stellar-background-ratio="0.5">
	<div class="overlay">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Enter the 6-digit code sent to your email</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	</header>

    <section class="verify-email-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="verify-email-card">
                        <form method="post" class="verify-email-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" class="form-control" name="verification_code" maxlength="6" placeholder="Kodni kiriting" required>
                            </div>
                            <button type="submit" class="btn btn-primary verify-email-btn">Check</button>
                            <a href="{% url 'accounts:login' %}" class="back-login">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer id="fh5co-footer" role="contentinfo">
        <div class="container">
            <div class="row row-pb-md justify-content-center text-center">
				<div class="col-md-3 fh5co-widget">
					<h4>About</h4>
					<p>You can learn programming in an online course. For example, you can learn c++, c#, python, java, javascript, php, etc. or learn through a tutorial</p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>Menu</h4>
					<ul class="fh5co-footer-links">
						<li><a href="{% url 'accounts:index' %}">Course</a></li>
						<li><a href="{% url 'categories' %}">Category</a></li>
						<li><a href="{% url 'prices' %}">Price</a></li>
						<li><a href="{% url 'blog' %}">Blog</a></li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>

            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <ul class="fh5co-social-icons">
                            <li><a href="https://t.me/musulmon_0319" target="_blank"><i class="fa-brands fa-telegram"></i></a></li>
                            <li><a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
                            <li><a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
                            <li><a href="https://freehtml5.co/" target="_blank"><i class="fa-brands fa-google"></i></a></li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    </div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/magnific-popup-options.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/modernizr-2.6.2.min.js' %}"></script>
    <script src="{% static 'assets/js/respond.min.js' %}"></script>
</body>
</html>

templates/accounts/password_reset_confirm.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<meta charset="utf-8">
	<title>Online Course</title>
	<meta http-equiv="x-ua-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co">
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive">
	<meta name="author" content="freehtml5.co">
	<meta property="og:title" content="">
	<meta property="og:image" content="">
	<meta property="og:url" content="">
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/imgs/mrx.jpg' %}">
	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
	<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	</head>
    <body>
		
	<div class="fh5co-loader"></div>
	
	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-xs-1">
						<div id="fh5co-logo"><a href="{% url 'accounts:index' %}">Course</a></div>
					</div>
					<div class="col-xs-11 text-right menu-1">
						<ul>
							<li><a href="{% url 'categories' %}">Category</a></li>
							<li><a href="{% url 'prices' %}">Price</a></li>
							<li><a href="{% url 'blog' %}">Blog</a></li>
							<li><a href="{% url 'contact' %}">Contact</a></li>
							<li class="btn-cta"><a href="{% url 'accounts:login' %}"><span>Login</span></a></li>
							<li class="btn-cta"><a href="{% url 'accounts:register' %}"><span>Register</span></a></li>
						</ul>
					</div>
				</div>
				
			</div>
		</div>
	</nav>

	<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url({% static 'assets/imgs/kurs.png' %});" data-stellar-background-ratio="0.5">
	<div class="overlay">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Reset New Password</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	</header>

    <section class="change-password-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="change-password-card">
                        <form method="post" class="change-password-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="password" class="form-control" name="password" placeholder="Yangi parol" required>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" name="confirm_password" placeholder="Parolni tasdiqlang" required>
                            </div>
                            <button type="submit" class="btn btn-primary change-password-btn">Save</button>
                            <a href="{% url 'accounts:login' %}" class="back-login">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>    

    <footer id="fh5co-footer" role="contentinfo">
        <div class="container">
            <div class="row row-pb-md justify-content-center text-center">
				<div class="col-md-3 fh5co-widget">
					<h4>About</h4>
					<p>You can learn programming in an online course. For example, you can learn c++, c#, python, java, javascript, php, etc. or learn through a tutorial</p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>Menu</h4>
					<ul class="fh5co-footer-links">
						<li><a href="{% url 'accounts:index' %}">Course</a></li>
						<li><a href="{% url 'categories' %}">Category</a></li>
						<li><a href="{% url 'prices' %}">Price</a></li>
						<li><a href="{% url 'blog' %}">Blog</a></li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>

            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <ul class="fh5co-social-icons">
                            <li><a href="https://t.me/musulmon_0319" target="_blank"><i class="fa-brands fa-telegram"></i></a></li>
                            <li><a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
                            <li><a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
                            <li><a href="https://freehtml5.co/" target="_blank"><i class="fa-brands fa-google"></i></a></li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    </div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/magnific-popup-options.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/modernizr-2.6.2.min.js' %}"></script>
    <script src="{% static 'assets/js/respond.min.js' %}"></script>
</body>
</html>

templates/accounts/password_reset_email.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
        }

        .email-container {
            width: 100%;
            max-width: 600px;
            margin: 0 auto;
            background-color: #ffffff;
            border: 1px solid #dddddd;
            border-radius: 5px;
        }

        .header {
            background-color: #007bff;
            color: #ffffff;
            text-align: center;
            padding: 20px;
        }

        .content {
            padding: 20px;
        }

        .image {
            max-width: 100%;
            height: auto;
        }

        .footer {
            background-color: #007bff;
            text-align : center;
            padding: 10px;
            font-size: 12px;
        }
    </style>    
</head>
<body>

    <div class="email-container text-center">
        <div class="header">
            <h1>This Email is send from Django project</h1>
        </div>
        <div class="content">
            <p>Hello {{ receiver_name }}</p>
            <p>This is a sample email template for Medium article</p>
            <p>Sizning parolingizni tiklash uchun kod: {{ code }}</p>
            <p>Bu kodni hech kimga bermang</p>
        </div>
    </div>
    
</body>
</html>

templates/accounts/password_reset_form.html
<!DOCTYPE HTML>
{% load static %}
<html>
	<head>
	<meta charset="utf-8">
	<title>Online Course</title>
	<meta http-equiv="x-ua-Compatible" content="ie=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Website Template by freehtml5.co">
	<meta name="keywords" content="free website templates, free html5, free template, free bootstrap, free website template, html5, css3, mobile first, responsive">
	<meta name="author" content="freehtml5.co">
	<meta property="og:title" content="">
	<meta property="og:image" content="">
	<meta property="og:url" content="">
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/imgs/mrx.jpg' %}">
	<link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"/>
	<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
	</head>
    <body>
		
	<div class="fh5co-loader"></div>
	
	<div id="page">
	<nav class="fh5co-nav" role="navigation">
		<div class="top-menu">
			<div class="container">
				<div class="row">
					<div class="col-xs-1">
						<div id="fh5co-logo"><a href="{% url 'accounts:index' %}">Course</a></div>
					</div>
					<div class="col-xs-11 text-right menu-1">
						<ul>
							<li><a href="{% url 'categories' %}">Category</a></li>
							<li><a href="{% url 'prices' %}">Price</a></li>
							<li><a href="{% url 'blog' %}">Blog</a></li>
							<li><a href="{% url 'contact' %}">Contact</a></li>
							<li class="btn-cta"><a href="{% url 'accounts:login' %}"><span>Login</span></a></li>
							<li class="btn-cta"><a href="{% url 'accounts:register' %}"><span>Register</span></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</nav>

	<header id="fh5co-header" class="fh5co-cover" role="banner" style="background-image:url({% static 'assets/imgs/kurs.png' %});" data-stellar-background-ratio="0.5">
	<div class="overlay">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center">
					<div class="display-t">
						<div class="display-tc animate-box" data-animate-effect="fadeIn">
							<h1>Reset password enter your email</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
    </div>
	</header>

    <section class="reset-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="reset-card">
                        <form method="post" class="reset-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="email" class="form-control" name="email" placeholder="Email manzilingiz" required>
                            </div>
                            <button type="submit" class="btn btn-primary reset-btn"> Send </button>
                            <a href="{% url 'accounts:login' %}" class="back-login">Cancel</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>    

    <footer id="fh5co-footer" role="contentinfo">
        <div class="container">
           <div class="row row-pb-md justify-content-center text-center">
				<div class="col-md-3 fh5co-widget">
					<h4>About</h4>
					<p>You can learn programming in an online course. For example, you can learn c++, c#, python, java, javascript, php, etc. or learn through a tutorial</p>
				</div>
				<div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
					<h4>Menu</h4>
					<ul class="fh5co-footer-links">
						<li><a href="{% url 'accounts:index' %}">Course</a></li>
						<li><a href="{% url 'categories' %}">Category</a></li>
						<li><a href="{% url 'prices' %}">Price</a></li>
						<li><a href="{% url 'blog' %}">Blog</a></li>
						<li><a href="{% url 'contact' %}">Contact</a></li>
					</ul>
				</div>
			</div>


            <div class="row copyright">
                <div class="col-md-12 text-center">
                    <p>
                        <ul class="fh5co-social-icons">
                            <li><a href="https://t.me/musulmon_0319" target="_blank"><i class="fa-brands fa-telegram"></i></a></li>
                            <li><a href="https://www.instagram.com/" target="_blank"><i class="fa-brands fa-instagram"></i></a></li>
                            <li><a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook"></i></a></li>
                            <li><a href="https://freehtml5.co/" target="_blank"><i class="fa-brands fa-google"></i></a></li>
                        </ul>
                    </p>
                </div>
            </div>
        </div>
    </footer>
    </div>
    <script src="{% static 'assets/js/jquery.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.easing.1.3.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.stellar.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
    <script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'assets/js/magnific-popup-options.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>
    <script src="{% static 'assets/js/modernizr-2.6.2.min.js' %}"></script>
    <script src="{% static 'assets/js/respond.min.js' %}"></script>
</body>
</html>